"""empty message

Revision ID: 1850dddbb522
Revises: 76079b6fb8dc
Create Date: 2022-05-25 18:00:19.872113

"""
from alembic import op
import sqlalchemy as sa
import homewerk


# revision identifiers, used by Alembic.
revision = '1850dddbb522'
down_revision = '76079b6fb8dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_subcriber',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', homewerk.models.base.BaseTimestamp(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', homewerk.models.base.BaseTimestamp(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_subcriber')
    # ### end Alembic commands ###
