"""empty message

Revision ID: 19b7879b1938
Revises: 946d2db67a23
Create Date: 2022-05-29 17:14:36.872440

"""
from alembic import op
import sqlalchemy as sa
import homewerk


# revision identifiers, used by Alembic.
revision = '19b7879b1938'
down_revision = '946d2db67a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', homewerk.models.base.BaseTimestamp(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', homewerk.models.base.BaseTimestamp(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved')
    # ### end Alembic commands ###
