"""empty message

Revision ID: 2a99c5699de8
Revises: 768bdbcd55fc
Create Date: 2022-06-05 11:02:48.810082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a99c5699de8'
down_revision = '768bdbcd55fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('max_score', sa.Integer(), nullable=True))
    op.add_column('assignments', sa.Column('score_type', sa.String(50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'score_type')
    op.drop_column('assignments', 'max_score')
    # ### end Alembic commands ###
