"""course clazz to class

Revision ID: 2ab53de03533
Revises: 99fd45e110a1
Create Date: 2022-04-16 09:38:06.509767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ab53de03533'
down_revision = '99fd45e110a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('class', sa.String(length=255), nullable=True))
    op.drop_column('courses', 'clazz')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('clazz', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('courses', 'class')
    # ### end Alembic commands ###
