"""empty message

Revision ID: 364abac430c0
Revises: dc06caa09faf
Create Date: 2022-05-02 14:45:33.947953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364abac430c0'
down_revision = 'dc06caa09faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submits', sa.Column('comment', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submits', 'comment')
    # ### end Alembic commands ###
