"""User unique usernam and gen data

Revision ID: 622b149df5e0
Revises: 2ab53de03533
Create Date: 2022-04-16 14:49:51.285742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622b149df5e0'
down_revision = '2ab53de03533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
