"""empty message

Revision ID: 677360954b27
Revises: c6e34ca60f17
Create Date: 2022-05-01 22:23:00.171146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '677360954b27'
down_revision = 'c6e34ca60f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_objects', 'width_size')
    op.add_column('works', sa.Column('width_size', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'width_size')
    op.add_column('work_objects', sa.Column('width_size', mysql.FLOAT(), nullable=False))
    # ### end Alembic commands ###
