"""empty message

Revision ID: 73da77d53a85
Revises: 1850dddbb522
Create Date: 2022-05-28 13:30:46.967079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73da77d53a85'
down_revision = '1850dddbb522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('scope_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'scope_id')
    # ### end Alembic commands ###
