"""empty message

Revision ID: 768bdbcd55fc
Revises: 8d9180e02310
Create Date: 2022-05-29 20:05:22.402771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768bdbcd55fc'
down_revision = '8d9180e02310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved', sa.Column('type_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved', 'type_name')
    # ### end Alembic commands ###
