"""empty message

Revision ID: 9617c009e97d
Revises: f386709788de
Create Date: 2022-07-23 16:14:53.986887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9617c009e97d'
down_revision = 'f386709788de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('attachment', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'attachment')
    # ### end Alembic commands ###
