"""empty message

Revision ID: 985c07b92807
Revises: 33c1915bc3c1
Create Date: 2022-04-23 19:15:57.830648

"""
from alembic import op
import sqlalchemy as sa
import homewerk


# revision identifiers, used by Alembic.
revision = '985c07b92807'
down_revision = '33c1915bc3c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('name', sa.String(length=155), nullable=False),
    sa.Column('due', sa.DateTime(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', homewerk.models.base.BaseTimestamp(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', homewerk.models.base.BaseTimestamp(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submits',
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', homewerk.models.base.BaseTimestamp(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', homewerk.models.base.BaseTimestamp(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('works',
    sa.Column('submit_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('canvas_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', homewerk.models.base.BaseTimestamp(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', homewerk.models.base.BaseTimestamp(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submit_id'], ['submits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_objects',
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('top', sa.Float(), nullable=False),
    sa.Column('left', sa.Float(), nullable=False),
    sa.Column('width_size', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', homewerk.models.base.BaseTimestamp(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', homewerk.models.base.BaseTimestamp(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_objects')
    op.drop_table('works')
    op.drop_table('submits')
    op.drop_table('assignments')
    # ### end Alembic commands ###
