"""empty message

Revision ID: 9ae2ff2a5e76
Revises: 364abac430c0
Create Date: 2022-05-08 14:43:48.832993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae2ff2a5e76'
down_revision = '364abac430c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('result_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'result_path')
    # ### end Alembic commands ###
