"""empty message

Revision ID: 9eb0b47e1216
Revises: a4955723faa1
Create Date: 2022-04-28 12:51:58.544190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb0b47e1216'
down_revision = 'a4955723faa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_course', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_course', 'active')
    # ### end Alembic commands ###
