"""User init

Revision ID: c3b4a8869626
Revises: c3491296d6c3
Create Date: 2022-04-15 21:33:08.116183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3b4a8869626'
down_revision = 'c3491296d6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('password', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('school', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('clazz', sa.String(length=255), nullable=True))
    op.drop_column('users', 'phonenumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phonenumber', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('users', 'clazz')
    op.drop_column('users', 'school')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'address')
    op.drop_column('users', 'email')
    op.drop_column('users', 'role')
    op.drop_column('users', 'password')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
