"""empty message

Revision ID: dc06caa09faf
Revises: e320269d92c2
Create Date: 2022-05-01 22:50:52.177730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc06caa09faf'
down_revision = 'e320269d92c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_objects', sa.Column('image', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_objects', 'image')
    # ### end Alembic commands ###
