"""empty message

Revision ID: e320269d92c2
Revises: 677360954b27
Create Date: 2022-05-01 22:23:45.678797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e320269d92c2'
down_revision = '677360954b27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_objects', sa.Column('width_size', sa.Float(), nullable=False))
    op.drop_column('works', 'width_size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('width_size', mysql.FLOAT(), nullable=False))
    op.drop_column('work_objects', 'width_size')
    # ### end Alembic commands ###
