"""empty message

Revision ID: e4cad66c7607
Revises: 622b149df5e0
Create Date: 2022-04-19 20:26:10.717706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4cad66c7607'
down_revision = '622b149df5e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_course', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user_course', 'course_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_course', 'course_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('user_course', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
