"""empty message

Revision ID: f9f55f3ade43
Revises: 19b7879b1938
Create Date: 2022-05-29 18:08:59.840985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f55f3ade43'
down_revision = '19b7879b1938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved', sa.Column('path', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved', 'path')
    # ### end Alembic commands ###
